"""Add ChatSession and update ChatHistory

Revision ID: 23b8f69a10cb
Revises: a5ba6b28cbbc
Create Date: 2025-07-28 15:39:52.002871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b8f69a10cb'
down_revision = 'a5ba6b28cbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=False))
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key('fk_chathistory_session_id', 'chat_session', ['session_id'], ['id'])  # <-- Name added here

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chathistory_session_id', type_='foreignkey')  # <-- Name added here
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('session_id')

    op.drop_table('chat_session')
    # ### end Alembic commands ###
