"""Add email field to User

Revision ID: a5ba6b28cbbc
Revises: ac15ada51191
Create Date: 2025-07-28 15:16:44.372257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ba6b28cbbc'
down_revision = 'ac15ada51191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['email'])  # <-- NAME ADDED HERE

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')  # <-- NAME ADDED HERE
        batch_op.drop_column('email')

    # ### end Alembic commands ###
